### ISSUE TITLE
réduire la taille de l'image docker

### ISSUE THREAD

**Issue by k3ck3c** [talentsconnect/awayboard#11]
en utilisant 

https://github.com/mhart/alpine-node

et donc en ayant en première ligne du Dockerfile

FROM mhart/alpine-node

on divise par 10 la taille de l'image docker

gg@asus:~$ docker images | grep awayboard
alpine_awayboard                        latest                                     dc54f756109d        5 days ago          77.2MB
awayboard                               latest                                     2119b7990eac        5 days ago          682MB

**Comment by foretspaisibles** [comment]
Comme ça? #12

**Comment by voodoocode** [comment]
Merci @k3ck3c 
Special thanks to my translator @michipili
